name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest


  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
